.

diff --git a/workbench b/workbench
--- a/workbench
+++ b/workbench
@@ -1,30 +1,36 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-run_script() {
+NAME="workbench"
 
+reinstall_workbench() {
+    bash <(curl -s https://raw.githubusercontent.com/randy3k/$NAME/master/install.sh)
 }
 
-update_bootstrap() {
-
+uninstall_workbench() {
+    rm -rf ~/.local/$NAME
+    rm ~/.local/bin/$NAME
 }
 
-PS3='Please choose an action: '
-options=("run" "update" )
 
-select opt in "${options[@]}"
-do
-    case $opt in
-        "run")
-            run_script
-            break
-            ;;
-        "update")
-            update_bootstrap
-            break
-            ;;
-        "quit")
-            break
-            ;;
-        *) echo "invalid option $REPLY";;
-    esac
-done
+case "$1" in
+    run)
+        shift
+        [ -z "$1" ] && echo "missing argument" && exit 1
+        FILE="$1"
+        shift
+        bash ~/.local/$NAME/run/$FILE.sh
+    ;;
+    list)
+        cd ~/.local/$NAME/run
+        ls -C1 *.sh | sed 's/\(.*\).sh/\1/'
+    ;;
+    reinstall)
+        reinstall_workbench
+    ;;
+    uninstall)
+        uninstall_workbench
+    ;;
+    *)
+        echo "Usage: workbench [list|run|sshkey|reinstall|uninstall]"
+    ;;
+esac
