add cat action

diff --git a/workbench b/workbench
--- a/workbench
+++ b/workbench
@@ -22,6 +22,13 @@ case "$1" in
         cd ~/.local/workbench/bin
         ls -C1 *.sh | sed 's/\(.*\).sh/\1/'
     ;;
+    cat)
+        shift
+        [ -z "$1" ] && echo "missing argument" && exit 1
+        FILE="$1"
+        shift
+        cat ~/.local/workbench/bin/$FILE.sh
+    ;;
     reinstall)
         reinstall_workbench
     ;;
@@ -29,6 +36,6 @@ case "$1" in
         uninstall_workbench
     ;;
     *)
-        echo "Usage: workbench [list|run|reinstall|uninstall]"
+        echo "Usage: workbench [list|run|cat|reinstall|uninstall]"
     ;;
 esac
